#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# the fuck
eval "$(thefuck --alias)"

# Export
source $HOME/.zexport

# Alias
source $HOME/.zalias

# Termcaps
bindkey  '^[[1;5A'   up-line-or-history
bindkey  '^[[1;5B'   down-line-or-history
bindkey  '^[[1;5D'   emacs-backward-word
bindkey  '^[[1;5C'   emacs-forward-word
bindkey  '^[[3;5~'   delete-word
bindkey   '^[[3~'    delete-char
